name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  install:
    name: ðŸ“¦ Install node modules
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18]
        pnpm-version: [7]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ matrix.pnpm-version }}

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}
      
      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: pnpm i


  build:
    name: ðŸš§ Nuxt build
    needs: install
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18]
        pnpm-version: [7]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ matrix.pnpm-version }}

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}
      
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('pnpm-lock.yaml') }}

      - name: ðŸ›  Nuxt Build
        run: pnpm build

  generate:
    name: ðŸš§ Nuxt generate
    needs: install
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18]
        pnpm-version: [7]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ matrix.pnpm-version }}

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}
      
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('pnpm-lock.yaml') }}
     
      - name: ðŸ›  Nuxt Generate
        run: pnpm generate
  
  
  lint:
    name: ðŸš§ Lint Check
    needs: install
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18]
        pnpm-version: [7]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ matrix.pnpm-version }}

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}
      
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('pnpm-lock.yaml') }}

      - name: ðŸ’ª Lint
        run: pnpm lint